### ISSUE TITLE
Add appendTo option to PrimeReact api 

### ISSUE THREAD

**Issue by mertsincan** [primefaces/primereact#1964]
Allows users to change the _appendTo_ property of all overlay components globally using PrimeReact.appendTo.

```
PrimeReact.appendTo = 'self' | HTMLElement | undefined | null;

Default is null. Therefore, all overlay components append to the body.
```

**Comment by bloodykheeng** [comment]
@mertsincan  @melloware  still append to doesnt work on the image component 
i wanted to do something like this

```
<Image 
 src={fileUrl} alt={fileName} width="150" preview downloadable 
  appendTo={mapIsFullscreen ? document.querySelector(".leaflet-container") : document.body}
 />;
```

but it fails it instead still shows behind the map 
and i end app getting this error each time i try to open two image components

```
Unexpected: global esc key listener with priority [400, 0] already exists. at Object.addListener (http://localhost:3001/static/js/bundle.js:371220:13) at http://localhost:3001/static/js/bundle.js:371241:38
```

these are my app versions
```
 "primeflex": "^4.0.0",
 "primeicons": "^7.0.0",
"primereact": "^10.9.7",
"react": "^18.3.1",
```
