### ISSUE TITLE
Bug in primereact's datatable demo

### ISSUE THREAD

**Issue by piperun** [primefaces/primereact#2700]
**I'm submitting a ...
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Current behavior**

If you press "sort by prices" menu in DataTable it gives the following error:
```Application error: a client-side exception has occurred (see the browser console for more information).```

And this console error:
```
framework-47503b8bb4de6bb8.js:1 ReferenceError: PrimeReact is not defined
    at 775-c515bc84a14dd1e8.js:1:5379
    at Array.sort (<anonymous>)
    at n.value (775-c515bc84a14dd1e8.js:1:5226)
    at n.value (775-c515bc84a14dd1e8.js:1:7495)
    at n.value (775-c515bc84a14dd1e8.js:1:7549)
    at $o (framework-47503b8bb4de6bb8.js:1:72066)
    at Bo (framework-47503b8bb4de6bb8.js:1:71863)
    at Hu (framework-47503b8bb4de6bb8.js:1:112966)
    at Pi (framework-47503b8bb4de6bb8.js:1:99067)
    at xi (framework-47503b8bb4de6bb8.js:1:98995)
uu @ framework-47503b8bb4de6bb8.js:1
a.componentDidCatch.n.callback @ framework-47503b8bb4de6bb8.js:1
fa @ framework-47503b8bb4de6bb8.js:1
hu @ framework-47503b8bb4de6bb8.js:1
Li @ framework-47503b8bb4de6bb8.js:1
t.unstable_runWithPriority @ framework-47503b8bb4de6bb8.js:1
$l @ framework-47503b8bb4de6bb8.js:1
Ti @ framework-47503b8bb4de6bb8.js:1
vi @ framework-47503b8bb4de6bb8.js:1
(anonymous) @ framework-47503b8bb4de6bb8.js:1
t.unstable_runWithPriority @ framework-47503b8bb4de6bb8.js:1
$l @ framework-47503b8bb4de6bb8.js:1
Ql @ framework-47503b8bb4de6bb8.js:1
Hl @ framework-47503b8bb4de6bb8.js:1
Me @ framework-47503b8bb4de6bb8.js:1
Xt @ framework-47503b8bb4de6bb8.js:1
main-671d20b532b6e5cc.js:1 ReferenceError: PrimeReact is not defined
    at 775-c515bc84a14dd1e8.js:1:5379
    at Array.sort (<anonymous>)
    at n.value (775-c515bc84a14dd1e8.js:1:5226)
    at n.value (775-c515bc84a14dd1e8.js:1:7495)
    at n.value (775-c515bc84a14dd1e8.js:1:7549)
    at $o (framework-47503b8bb4de6bb8.js:1:72066)
    at Bo (framework-47503b8bb4de6bb8.js:1:71863)
    at Hu (framework-47503b8bb4de6bb8.js:1:112966)
    at Pi (framework-47503b8bb4de6bb8.js:1:99067)
    at xi (framework-47503b8bb4de6bb8.js:1:98995)
ye @ main-671d20b532b6e5cc.js:1
fn @ main-671d20b532b6e5cc.js:1
value @ main-671d20b532b6e5cc.js:1
a.componentDidCatch.n.callback @ framework-47503b8bb4de6bb8.js:1
fa @ framework-47503b8bb4de6bb8.js:1
hu @ framework-47503b8bb4de6bb8.js:1
Li @ framework-47503b8bb4de6bb8.js:1
t.unstable_runWithPriority @ framework-47503b8bb4de6bb8.js:1
$l @ framework-47503b8bb4de6bb8.js:1
Ti @ framework-47503b8bb4de6bb8.js:1
vi @ framework-47503b8bb4de6bb8.js:1
(anonymous) @ framework-47503b8bb4de6bb8.js:1
t.unstable_runWithPriority @ framework-47503b8bb4de6bb8.js:1
$l @ framework-47503b8bb4de6bb8.js:1
Ql @ framework-47503b8bb4de6bb8.js:1
Hl @ framework-47503b8bb4de6bb8.js:1
Me @ framework-47503b8bb4de6bb8.js:1
Xt @ framework-47503b8bb4de6bb8.js:1
main-671d20b532b6e5cc.js:1 A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred
ye @ main-671d20b532b6e5cc.js:1
fn @ main-671d20b532b6e5cc.js:1
value @ main-671d20b532b6e5cc.js:1
a.componentDidCatch.n.callback @ framework-47503b8bb4de6bb8.js:1
fa @ framework-47503b8bb4de6bb8.js:1
hu @ framework-47503b8bb4de6bb8.js:1
Li @ framework-47503b8bb4de6bb8.js:1
t.unstable_runWithPriority @ framework-47503b8bb4de6bb8.js:1
$l @ framework-47503b8bb4de6bb8.js:1
Ti @ framework-47503b8bb4de6bb8.js:1
vi @ framework-47503b8bb4de6bb8.js:1
(anonymous) @ framework-47503b8bb4de6bb8.js:1
t.unstable_runWithPriority @ framework-47503b8bb4de6bb8.js:1
$l @ framework-47503b8bb4de6bb8.js:1
Ql @ framework-47503b8bb4de6bb8.js:1
Hl @ framework-47503b8bb4de6bb8.js:1
Me @ framework-47503b8bb4de6bb8.js:1
Xt @ framework-47503b8bb4de6bb8.js:1
```

**Expected behavior**
It would sort the prices by low/high.

**Minimal reproduction of the problem with instructions**
Simply go to primereact and to DataTable demo with prices and click on the menu labeled "Sort by price" and choose 1 option and it should replicate the error above.

**Please tell us about your environment:**

Windows 10

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 Chrome 99, Firefox 96

**Comment by melloware** [comment]
@piperun I can't reproduce on the showcase the sort by price is working fine?  See: https://primefaces.org/primereact/datatable/sort/

Are you doing something that I am not doing?

**Comment by piperun** [comment]
> @piperun I can't reproduce on the showcase the sort by price is working fine? See: https://primefaces.org/primereact/datatable/sort/
> 
> Are you doing something that I am not doing?

Sorry I mistook the component, it's the DataView that is bugged:
https://primefaces.org/primereact/dataview/

**Comment by melloware** [comment]
OK already fixed see this issue: https://github.com/primefaces/primereact/issues/2663

Will be in the next release.  Please close this ticket thanks!
