### ISSUE TITLE
Charts: Explicit import of chart.js dependency doesn't allow for single pages with inline scripting

### ISSUE THREAD

**Issue by tailg8nj** [primefaces/primereact#3059]
Unless I'm misunderstanding something here, I believe the following line that imports `chart.js/auto`, means that in order to use the PrimeReact Graph components, you must be using a node-based installation. I have not found a way to successfully leverage them via [script tags](https://www.chartjs.org/docs/latest/getting-started/integration.html#script-tag).

https://github.com/primefaces/primereact/blob/f80c1fe033ccd7e3d3cf34356a7373c1e3ac957c/components/lib/chart/Chart.js#L10

Example code that fails:

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Chart Example</title>

    <!-- PrimeReact -->
    <link rel="stylesheet" href="https://unpkg.com/primeicons/primeicons.css" />
    <link rel="stylesheet" href="https://unpkg.com/primereact/resources/themes/lara-light-indigo/theme.css" />
    <link rel="stylesheet" href="https://unpkg.com/primereact/resources/primereact.min.css" />
    <link rel="stylesheet" href="https://unpkg.com/primeflex@2.0.0/primeflex.min.css" />

    <!-- Dependencies -->
    <script src="https://unpkg.com/react/umd/react.production.min.js"></script>
    <script src="https://unpkg.com/react-dom/umd/react-dom.production.min.js"></script>
    <script src="https://unpkg.com/@babel/standalone/babel.min.js"></script>
    <script src="https://unpkg.com/react-transition-group@4.4.2/dist/react-transition-group.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/3.8.0/chart.min.js" crossorigin="anonymous"></script>

    <!-- Demo -->
    <script src="https://unpkg.com/primereact/core/core.min.js"></script>
    <script src="https://unpkg.com/primereact/chart/chart.min.js" crossorigin="anonymous"></script>
</head>
<body>
    <div id="root"></div>

    <script type="text/babel">

        const { useEffect, useState } = React;
        const { Chart } = primereact.chart;

        const data = {
        labels: ['January', 'February', 'March', 'April', 'May', 'June', 'July'],
            datasets: [
                {
                    label: 'First Dataset',
                    data: [65, 59, 80, 81, 56, 55, 40],
                    fill: false,
                    borderColor: '#4bc0c0'
                }
            ]
        };

        const ChartDemo = () => {
            return (
                <div className="chart-demo">
                    <div className="card">
                        <Chart type="line" data={data} />
                    </div>
                </div>
            );
        }

        const rootElement = document.getElementById("root");
        ReactDOM.render(<ChartDemo />, rootElement);

    </script>
</body>
</html>
```

Stack:
```
Uncaught (in promise) TypeError: Failed to resolve module specifier 'chart.js/auto'
    at chart.min.js:1:1012
    at Id (react-dom.production.min.js:165:137)
    at Xb (react-dom.production.min.js:200:284)
    at react-dom.production.min.js:197:106
    at S (react.production.min.js:17:25)
    at MessagePort.U (react.production.min.js:21:60)
```

Opening this issue to confirm and any suggested work-arounds. I have a fairly simple form that needs to query a rest server and display the chart. I'd love to use the charting available here instead of say, plotly or returning svg/png data.

**Comment by melloware** [comment]
Thanks for reporting.  I think that you might be correct that this won't work.  I just recently fixed this: https://github.com/primefaces/primereact/issues/2999

I think we have to try and make another fix to load it if its loaded via script.

**Comment by melloware** [comment]
Looks like this: https://www.chartjs.org/docs/latest/getting-started/integration.html  Just need to figure out how.

**Comment by melloware** [comment]
Currently this doesn't look possible because the name of the React component `Chart` is colliding with ChartsJS `new Chart`

**Comment by tailg8nj** [comment]
> Currently this doesn't look possible because the name of the React component `Chart` is colliding with ChartsJS `new Chart`

I looked at your commit / attempt. Would we be able to leverage the `export as` syntax here with a temporary name for the React Chart? e.g.:

```javascript
const PrimeReactChart = React.memo(React.forwardRef((props, ref) => {

    const chartRef = React.useRef(null);
    const canvasRef = React.useRef(null);

    const initChart = () => {

        // lines omitted 

        if (Chart) {
            // GitHub #3059 loaded by script only
            chartRef.current = new Chart(canvasRef.current, configuration);
        }
        else {
            import('chart.js/auto').then((module) => {
                if (module) {
                    if (module.default) {
                        // WebPack
                        chartRef.current = new module.default(canvasRef.current, configuration);
                    } else {
                        // ParcelJs
                        chartRef.current = new module(canvasRef.current, configuration);
                    }
                }
            });
        }
    }

    // lines omitted

    return (
        <div id={props.id} style={style} className={className} {...otherProps}>
            <canvas ref={canvasRef} width={props.width} height={props.height}></canvas>
        </div>
    );
}), (prevProps, nextProps) => prevProps.data === nextProps.data && prevProps.options === nextProps.options && prevProps.type === nextProps.type);

PrimeReactChart.displayName = 'Chart';
PrimeReactChart.defaultProps = {
    __TYPE: 'Chart',
    id: null,
    type: null,
    data: null,
    options: null,
    plugins: null,
    width: null,
    height: null,
    style: null,
    className: null
}

export { PrimeReactChart as Chart };
```

**Comment by melloware** [comment]
Yes let me try this that looks really promising!

**Comment by melloware** [comment]
OK PR submitted!  Tested and its still working fine in NextJS/CRA.

**Comment by tailg8nj** [comment]
Confirmed working as expected.

**Comment by mertsincan** [comment]
Ohh no! I did not expect such a quick effect :) You are very fast :D
