### ISSUE TITLE
Autocomplete (multiple) rendered fewer hooks than previous

### ISSUE THREAD

**Issue by monsteradurm** [primefaces/primereact#3431]
I receive an error after attempting to add multiple items to an autocomplete component.

It takes 2 or 3 items to be added before the issue occurs.

`The above error occurred in the <AutoCompletePanel> component:

    at http://localhost:3000/static/js/bundle.js:147149:17
    at span
    at http://localhost:3000/static/js/bundle.js:147157:75
    at span
    at div
    at http://localhost:3000/static/js/bundle.js:182787:9
    at div
    at http://localhost:3000/static/js/bundle.js:182787:9
    at div
    at div
    at Transition (http://localhost:3000/static/js/bundle.js:219695:30)
    at CSSTransition (http://localhost:3000/static/js/bundle.js:219245:35)
    at http://localhost:3000/static/js/bundle.js:153032:24
    at div
    at http://localhost:3000/static/js/bundle.js:158633:75
    at http://localhost:3000/static/js/bundle.js:153402:75
    at NewTicketDialog (http://localhost:3000/static/js/bundle.js:21661:7)
    at Router (http://localhost:3000/static/js/bundle.js:218993:15)
    at BrowserRouter (http://localhost:3000/static/js/bundle.js:217802:5)
    at div
    at App (http://localhost:3000/static/js/bundle.js:624:93)
    at MsalProvider (http://localhost:3000/static/js/bundle.js:48515:5)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
logCapturedError @ bundle.js:202157
bundle.js:210220 Uncaught Error: Rendered more hooks than during the previous render.
    at updateWorkInProgressHook (bundle.js:200013:17)
    at updateReducer (bundle.js:200074:18)
    at updateState (bundle.js:200501:14)
    at Object.useState (bundle.js:201397:20)
    at useState (bundle.js:224795:25)
    at useStateObservable (bundle.js:116483:71)
    at bundle.js:116542:12
    at ItemTemplate (bundle.js:21728:90)
    at Function.getJSXElement (bundle.js:162785:41)
    at createItem (bundle.js:147055:101)`

`if (nextWorkInProgressHook !== null) {
        // There's already a work-in-progress. Reuse it.
        workInProgressHook = nextWorkInProgressHook;
        nextWorkInProgressHook = workInProgressHook.next;
        currentHook = nextCurrentHook;
      } else {
        // Clone from the current hook.
        if (nextCurrentHook === null) {
          throw new Error('Rendered more hooks than during the previous render.');
        }`

**Comment by monsteradurm** [comment]
Found an additional error mesage:

`react_devtools_backend.js:4026 Warning: React has detected a change in the order of Hooks called by AutoCompletePanel. This will lead to bugs and errors if not fixed. For more information, read the Rules of Hooks: https://reactjs.org/link/rules-of-hooks

   Previous render            Next render
   ------------------------------------------------------
1. useContext                 useContext
2. useState                   useState
3. useRef                     useRef
4. useSyncExternalStore       useSyncExternalStore
5. useState                   useState
6. useEffect                  useEffect
7. undefined                  useContext
   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

    at http://localhost:3000/static/js/bundle.js:147149:17
    at span
    at http://localhost:3000/static/js/bundle.js:147157:75
    at span
    at div
    at http://localhost:3000/static/js/bundle.js:182787:9
    at div
    at http://localhost:3000/static/js/bundle.js:182787:9
    at div
    at div
    at Transition (http://localhost:3000/static/js/bundle.js:219695:30)
    at CSSTransition (http://localhost:3000/static/js/bundle.js:219245:35)
    at http://localhost:3000/static/js/bundle.js:153032:24
    at div
    at http://localhost:3000/static/js/bundle.js:158633:75
    at http://localhost:3000/static/js/bundle.js:153402:75
    at NewTicketDialog (http://localhost:3000/static/js/bundle.js:21661:7)
    at Router (http://localhost:3000/static/js/bundle.js:218993:15)
    at BrowserRouter (http://localhost:3000/static/js/bundle.js:217802:5)
    at div
    at App (http://localhost:3000/static/js/bundle.js:624:93)
    at MsalProvider (http://localhost:3000/static/js/bundle.js:48515:5)`

**Comment by monsteradurm** [comment]
Additionally there is this error message when ever the user starts typing...

`Warning: Internal React error: Expected static flag was missing. Please notify the React team.
    at http://localhost:3000/static/js/bundle.js:147149:17
    at span
    at http://localhost:3000/static/js/bundle.js:147157:75
    at span
    at div
    at http://localhost:3000/static/js/bundle.js:182787:9
    at div
    at http://localhost:3000/static/js/bundle.js:182787:9
    at div
    at div
    at Transition (http://localhost:3000/static/js/bundle.js:219695:30)
    at CSSTransition (http://localhost:3000/static/js/bundle.js:219245:35)
    at http://localhost:3000/static/js/bundle.js:153032:24
    at div
    at http://localhost:3000/static/js/bundle.js:158633:75
    at http://localhost:3000/static/js/bundle.js:153402:75
    at NewTicketDialog (http://localhost:3000/static/js/bundle.js:21661:7)
    at Router (http://localhost:3000/static/js/bundle.js:218993:15)
    at BrowserRouter (http://localhost:3000/static/js/bundle.js:217802:5)
    at div
    at App (http://localhost:3000/static/js/bundle.js:624:93)
    at MsalProvider (http://localhost:3000/static/js/bundle.js:48515:5)`

**Comment by melloware** [comment]
@monsteradurm going to close for now I will re-open if you can provide a reproducible test case.

**Comment by monsteradurm** [comment]
Thanks. I was writing up the example in code sandbox and in the process im fairly sure ive figured out the issue - though i havent got a workaround yet.

In my Item template I was calling a hook..

```
const ItemTemplate = (tag) => {`
    const photo = useUserPhotoByName(tag.user.name);
    .....
}
```

which would probably explain why it renders more/less hooks depending on how many users are filtered. Apologies for the run around - guess the templates cant be used in this manner ( probably obvious to everyone else ).

**Comment by monsteradurm** [comment]
Yes, just following up on the above again.. using a component inside the function intead of treating the function like a component did the trick. Sorry - realise this was a newby issue.

const ItemTemplate = (tag) => <ItemComponent tag={tag} />
