### ISSUE TITLE
primereact.min.css Error at background:transparent URL() with base64 image

### ISSUE THREAD

**Issue by maaelphd** [primefaces/primereact#4097]
### Describe the bug

I'm using primereact, and on css primereact.min.css, when i run my app, i'm receving this error:

```ERROR in data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABEAAACWCAIAAAC3uvTNAAAA7ElEQVRYw+2YUQqDQAxEh9GWuqV6Be9/JT88RN0VRUuv0ElBwhKY3yF5m90kLKd+mF/975r6geNyjm9Fy0kgqTJ6nqoIdGKczjmPJU5tZxA8wWPL7YOHKhZAlcmTAVVcxSCrMbfgqY/H6JEOoASPe56tgSrqLR7U2zWojwWjJ3jq47HEiZoGTwJxP1RRXw8y9RZfCMhbhTHOVTxXnUFtPJ5rGjzu35y2KfKGQxWT2K4TQL1d2zz6KAH1kRU8wfOXx+37qY3Hct+aDaqot2u7R/wMuDS3qnj0z0HqK4X/+kRNHdfUwFP2Nisqe/sFuUZiVjC9HCUAAAAASUVORK5CYII=
Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: D:\Codigo\node_projects\myproject\project_1\data:image\png;base64,iVBORw0KGgoAAAANSUhEUgAAABEAAACWCAIAAAC3uvTNAAAA7ElEQVRYw+2YUQqDQAxEh9GWuqV6Be9\JT88RN0VRUuv0ElBwhKY3yF5m90kLKd+mF\975r6geNyjm9Fy0kgqTJ6nqoIdGKczjmPJU5tZxA8wWPL7YOHKhZAlcmTAVVcxSCrMbfgqY\H6JEOoASPe56tgSrqLR7U2zWojwWjJ3jq47HEiZoGTwJxP1RRXw8y9RZfCMhbhTHOVTxXnUFtPJ5rGjzu35y2KfKGQxWT2K4TQL1d2zz6KAH1kRU8wfOXx+37qY3Hct+aDaqot2u7R\wMuDS3qnj0z0HqK4X\+kRNHdfUwFP2Nisqe\sFuUZiVjC9HCUAAAAASUVORK5CYII=: Unexpected character '�'. (1:0)

> 1 | �PNG
    | ^
  2 | →
  3 |
  4 | IHDR◄☻�����IDATX��Q
    at instantiate (D:\Codigo\node_projects\myproject\project_1\node_modules\@babel\parser\lib\index.js:64:32)
    at constructor (D:\Codigo\node_projects\myproject\project_1\node_modules\@babel\parser\lib\index.js:364:12)
    at JSXParserMixin.raise (D:\Codigo\node_projects\myproject\project_1\node_modules\@babel\parser\lib\index.js:3253:19)
    at JSXParserMixin.getTokenFromCode (D:\Codigo\node_projects\myproject\project_1\node_modules\@babel\parser\lib\index.js:2914:16)
    at JSXParserMixin.getTokenFromCode (D:\Codigo\node_projects\myproject\project_1\node_modules\@babel\parser\lib\index.js:7020:18)
    at JSXParserMixin.nextToken (D:\Codigo\node_projects\myproject\project_1\node_modules\@babel\parser\lib\index.js:2376:10)
    at JSXParserMixin.parse (D:\Codigo\node_projects\myproject\project_1\node_modules\@babel\parser\lib\index.js:14248:10)
    at parse (D:\Codigo\node_projects\myproject\project_1\node_modules\@babel\parser\lib\index.js:14292:38)
    at parser (D:\Codigo\node_projects\myproject\project_1\node_modules\@babel\core\lib\parser\index.js:52:34)
    at parser.next (<anonymous>)
 @ ./node_modules/css-loader/dist/cjs.js!./node_modules/sass-loader/dist/cjs.js!./node_modules/primereact/resources/primereact.min.css 6:36-478
 @ ./node_modules/primereact/resources/primereact.min.css 8:6-128 22:17-24 26:7-21 58:25-39 59:36-47 59:50-64 63:6-73:7 64:54-65 64:68-82 70:42-53 70:56-70 72:21-28 83:0-98 83:0-98 84:22-29 84:33-47 84:50-64 61:4-74:5
 @ ./src/AppLayout.js 28:0-49
 @ ./src/App.js 26:9-57
 @ ./src/index.js 3:0-27 5:50-53
```

Looking at primereact.min.css where, i've found the property, that load a base64 img from url().
Like this:
```background:transparent url("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABEAAACWCAIAAAC3uvTNAAAA7ElEQVRYw+2YUQqDQAxEh9GWuqV6Be9/JT88RN0VRUuv0ElBwhKY3yF5m90kLKd+mF/975r6geNyjm9Fy0kgqTJ6nqoIdGKczjmPJU5tZxA8wWPL7YOHKhZAlcmTAVVcxSCrMbfgqY/H6JEOoASPe56tgSrqLR7U2zWojwWjJ3jq47HEiZoGTwJxP1RRXw8y9RZfCMhbhTHOVTxXnUFtPJ5rGjzu35y2KfKGQxWT2K4TQL1d2zz6KAH1kRU8wfOXx+37qY3Hct+aDaqot2u7R/wMuDS3qnj0z0HqK4X/+kRNHdfUwFP2Nisqe/sFuUZiVjC9HCUAAAAASUVORK5CYII=")```

Anyone haveing this issue? when using base64 in url() ? I'm looked for somes older versions from PrimeReact, and i have found one version that not appears this error, and looking at this same .css code, they use the previous code just like this:
```background:transparent url("./images/hue.png")``` 
Instead of using a base64 image.

**my package.json:** 

```
"dependencies": {
    "@babel/core": "^7.15.5",
    "@babel/preset-env": "^7.15.6",
    "@types/react": "18.0.26",
    "primeflex": "^3.3.0",
    "primeicons": "^6.0.1",
    "primereact": "^9.2.0",
    "react": "^18.2.0",
    "react-dom": "18.2.0",
    "react-scripts": "3.0.1",
    "react-transition-group": "^2.9.0",
  },
  "devDependencies": {
    "css-loader": "^6.7.3",
    "node-sass": "^6.0.1",
    "sass-loader": "^13.2.0",
    "style-loader": "^3.3.1",
    "terser-webpack-plugin": "^5.3.6",
    "webpack": "^5.75.0",
    "webpack-bundle-analyzer": "^4.8.0",
    "webpack-cli": "^5.0.1",
    "webpack-dev-server": "^4.11.1"
  },
```

**my webpack.config.js:**

```
module.exports = [
  {
    module: {
      rules: [
        ...
        {
          exclude: /node_modules/,
          loader: 'babel-loader',
          options: {
            plugins: [
              'transform-class-properties',
              ['import', { libraryName: 'antd', style: 'css' }],
            ],
          },
        },
        {
          test:/\.(s*)css$/,
          use:['style-loader', 'css-loader', 'sass-loader']
        },
        {
          test: /\.(woff(2)?|ttf|eot|svg|jpe?g|png|webp|gif)(\?v=\d+\.\d+\.\d+)?$/,
          use: [
            {
              loader: 'url-loader',
              options: {
                limit: 819200,
                name: '[name].[ext]',
                outputPath: 'img/',
                esModule: false,
              },
            },
          ],
          type: 'javascript/auto'
        },
      ],
    },
  },
]
```

**npx webpack-cli info:**

```System:
    OS: Windows 10 10.0.19044
    CPU: (16) x64 AMD Ryzen 7 5800X 8-Core Processor
    Memory: 20.68 GB / 31.95 GB
  Binaries:
    Node: 16.13.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.5.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (110.0.1587.56)
    Internet Explorer: 11.0.19041.1566
  Packages:
    babel-loader: ^9.1.2 => 9.1.2
    babel-minify-webpack-plugin: ^0.3.1 => 0.3.1
    compression-webpack-plugin: ^9.0.0 => 9.2.0
    css-loader: ^6.7.3 => 6.7.3
    extract-text-webpack-plugin: ^4.0.0-beta.0 => 4.0.0-beta.0
    file-loader: ^6.2.0 => 6.2.0
    html-webpack-change-assets-extension-plugin: ^1.2.0 => 1.3.0
    html-webpack-plugin: ^5.3.2 => 5.5.0
    node-polyfill-webpack-plugin: ^1.1.4 => 1.1.4
    resolve-url-loader: ^3.1.1 => 3.1.4
    sass-loader: ^13.2.0 => 13.2.0
    style-loader: ^3.3.1 => 3.3.1
    terser-webpack-plugin: ^5.3.6 => 5.3.6
    url-loader: ^4.1.0 => 4.1.1
    webpack: ^5.75.0 => 5.75.0
    webpack-bundle-analyzer: ^4.8.0 => 4.8.0
    webpack-cli: ^5.0.1 => 5.0.1
    webpack-dev-server: ^4.11.1 => 4.11.1```

### Reproducer

_No response_

### PrimeReact version

9.2.0

### React version

18.x

### Language

ES5

### Build / Runtime

Create React App (CRA)

### Browser(s)

Opera, Chrome, Edge

### Steps to reproduce the behavior

I just have webpack, babel and css-loader. Using that with prime, i have this issue

### Expected behavior

_No response_

**Comment by melloware** [comment]
Aasigned to PrimeTek to review.

**Comment by mertsincan** [comment]
Thanks a lot for your report! We'll check it and get back to you.

**Comment by mertsincan** [comment]
Fixed in https://github.com/primefaces/primereact/commit/86ad8aeaf69aea6eae28eaea37fa583cb88bfb2f
