### ISSUE TITLE
Build: missing `components/lib/common/Common.css`

### ISSUE THREAD

**Issue by mondaychen** [primefaces/primereact#4889]
### Describe the bug

I tried to run `npm run build:lib` and hit the following error
```
[17:11:01] 'build-css' errored after 5.8 ms
[17:11:01] Error: File not found with singular glob: /Users/mengdi/workspace/primereact/components/lib/common/Common.css (if this was purposeful, use `allowEmpty` option)
    at Glob.<anonymous> (/Users/mengdi/workspace/primereact/node_modules/glob-stream/readable.js:84:17)
    at Object.onceWrapper (node:events:629:26)
    at Glob.emit (node:events:514:28)
    at Glob.emit (node:domain:489:12)
    at Glob._finish (/Users/mengdi/workspace/primereact/node_modules/glob-stream/node_modules/glob/glob.js:194:8)
    at done (/Users/mengdi/workspace/primereact/node_modules/glob-stream/node_modules/glob/glob.js:179:14)
    at Glob._processSimple2 (/Users/mengdi/workspace/primereact/node_modules/glob-stream/node_modules/glob/glob.js:688:12)
    at /Users/mengdi/workspace/primereact/node_modules/glob-stream/node_modules/glob/glob.js:676:10
    at Glob._stat2 (/Users/mengdi/workspace/primereact/node_modules/glob-stream/node_modules/glob/glob.js:772:12)
    at lstatcb_ (/Users/mengdi/workspace/primereact/node_modules/glob-stream/node_modules/glob/glob.js:764:12)
[17:11:01] 'build-resources' errored after 7.07 ms
```

Looks like this file existed on 9.6.2 but has been missing since b72553503c501c680dd398791242e84093f0dc6e. 

### PrimeReact version

9.7.0

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

`npm run build:lib`

**Comment by melloware** [comment]
Thanks let me check it out.

**Comment by melloware** [comment]
@mondaychen can you pull the v9.7.0 branch and try again? I made some fixes and the build is working for me.

**Comment by melloware** [comment]
Nope not documented.  I also fixed `master` if you want to try that.
