### ISSUE TITLE
DataTable: Error when updating a cell

### ISSUE THREAD

**Issue by BAISTM** [primefaces/primereact#5556]
### Describe the bug

I've got the below console error when updating a cell

![image](https://github.com/primefaces/primereact/assets/129836651/a8a73a83-376a-419b-8786-9cc608324211)

**Minimal code reproduction**:

```js
export default function PrimeDataTable() {
  const [data, setData] = React.useState([
    {
      value: '2',
    },
  ]);
  return (
    <DataTable value={data}>
      <Column
        field="value"
        editor={options => (
          <input
            value={options.value}
            onChange={event => options.editorCallback?.(event.target.value)}
          />
        )}
        onCellEditComplete={({ newValue }) => {
          setData([{ value: newValue }]);
        }}
      />
    </DataTable>
  );
}
```

### Reproducer

https://codesandbox.io/p/sandbox/primereact-demo-forked-v94dr7?file=%2Fsrc%2FApp.js

### PrimeReact version

10.1.1

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

1. Use a DataTable with cell edit mode
2. Update a React state inside the onCellEditComplete

### Expected behavior

The error `Cannot update a component` should not be displayed in the console.

**Comment by melloware** [comment]
Your reproducer works fine for me.

also you are doing it wrong from your example.

```js
onValueChange={(e) => options.editorCallback(e.value)}
```
Already handles changing the `data` state for you and you try and do it again by doing it on the onCompleteEdit firing the hook again triggering the datatable again.

That is not how cell editing works.

**Comment by BAISTM** [comment]
Hello @melloware,

My reproducer works functionally, but it triggers a React error in the console.

Sorry, but I don't understand what's wrong in my example.

The `onChange` updates the state of the input when the editing mode is enabled and the` onCompleteEdit` synchronize the data when the edition is validated.

How can I synchronize DataTable data without using `onCompleteEdit` hook ?

Thank you for your response.

**Comment by BAISTM** [comment]
I've got the bellow error on editing a quantity, can you retry plz? Thank you!

```
Warning: Cannot update a component (`CellEditingDemo`) while rendering a different component (`BodyCell`). To locate the bad setState() call inside `BodyCell`, follow the stack trace as described in https://reactjs.org/link/setstate-in-render
    at eval (https://v94dr7.csb.app/node_modules/primereact/datatable/datatable.esm.js:883:46)
    at tr
    at eval (https://v94dr7.csb.app/node_modules/primereact/datatable/datatable.esm.js:1612:31)
    at tbody
    at eval (https://v94dr7.csb.app/node_modules/primereact/datatable/datatable.esm.js:2133:34)
    at table
    at eval (https://v94dr7.csb.app/node_modules/primereact/virtualscroller/virtualscroller.esm.js:178:23)
    at div
    at div
    at eval (https://v94dr7.csb.app/node_modules/primereact/datatable/datatable.esm.js:4981:23)
    at div
    at CellEditingDemo (https://v94dr7.csb.app/src/App.js:20:55)
    at PrimeReactProvider (https://v94dr7.csb.app/node_modules/primereact/api/api.esm.js:997:26)
```

**Comment by BAISTM** [comment]
IMHO, this warning is due to this state update https://github.com/primefaces/primereact/blob/master/components/lib/datatable/BodyCell.js#L71C1-L73C6.

According to https://github.com/facebook/react/issues/18178#issuecomment-595846312,  a `setState` should be wrapped in a `useEffect`.

Thank you :)

**Comment by melloware** [comment]
OK PR Submitted.  Good catch.

**Comment by BAISTM** [comment]
Thank you :)

**Comment by melloware** [comment]
A bunch of changes accidentally got rolled back.  I am adding them back in now.

**Comment by FAMSTM** [comment]
@melloware With v10.3.1, there is still the issue, this ticket should be reopened?

**Comment by melloware** [comment]
Weird.  Let me look again because locally running in NextJS this was working without the warning error after this change.

**Comment by melloware** [comment]
@BAISTM I am able to reproduce it locally.  Very strange but the stack trace line numbers don't really help. This is weird.
