### ISSUE TITLE
Mention - autoResize

### ISSUE THREAD

**Issue by Nandovga** [primefaces/primereact#6296]
### Describe the bug

By passing the autorize property as true within a modal. DOM element error.

```
chunk-CXJOIMMF.js?v=f8bbd99b:521 Warning: React does not recognize the `autoResize` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `autoresize` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    at div
    at http://[::1]:5173/node_modules/.vite/deps/primereact_mention.js?v=f8bbd99b:418:20
    at div
    at div
    at Comment (http://[::1]:5173/resources/react/Crm/Atendimento/Requisito/Home/View/Comment.tsx?t=1712153646287:25:24)
    at div
    at div
    at TabViewBootstrap (http://[::1]:5173/node_modules/orangecode-react-components/src/react/TabView.tsx:3:29)
    at TabView (http://[::1]:5173/node_modules/orangecode-react-components/src/react/TabView.tsx:77:20)
    at div
    at Descricao (http://[::1]:5173/resources/react/Crm/Atendimento/Requisito/Home/View/Descricao.tsx?t=1712153587802:26:24)
    at div
    at div
    at div
    at div
    at div
    at ModalBootstrap (http://[::1]:5173/node_modules/orangecode-react-components/src/react/Modal.tsx:5:27)
    at Modal (http://[::1]:5173/node_modules/orangecode-react-components/src/react/Modal.tsx:125:18)
    at View (http://[::1]:5173/resources/react/Crm/Atendimento/Requisito/Home/View.tsx?t=1712153587802:29:37)
    at FormProvider (http://[::1]:5173/node_modules/.vite/deps/chunk-SFL2ETDO.js?v=f8bbd99b:80:11)
    at Index (http://[::1]:5173/resources/react/Crm/Atendimento/Requisito/Home/Index.tsx?t=1712153587802:50:35)
    at w2 (http://[::1]:5173/node_modules/.vite/deps/@inertiajs_react.js?v=f8bbd99b:3597:25)
    at PrimeReactProvider2 (http://[::1]:5173/node_modules/.vite/deps/chunk-MDBMXJA5.js?v=f8bbd99b:3092:26)
```

### PrimeReact version

10.5.1

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

Chrome

**Comment by melloware** [comment]
Duplciate of https://github.com/primefaces/primereact/issues/7367 which has a reproducer so closing this one

**Comment by melloware** [comment]
Fixed in next release
