### ISSUE TITLE
InputOtp: Value is read-only (even if readOnly prop isn't set or false)

### ISSUE THREAD

**Issue by AndrewMamdouh** [primefaces/primereact#6432]
### Describe the bug

By changing `InputOtp` value, It raises an error and value can't be changed:
```
VM3144 inputotp.esm.js:53 Uncaught TypeError: "newTokens" is read-only
    at _readOnlyError (VM3144 inputotp.esm.js:53:11)
    at updateTokens (VM3144 inputotp.esm.js:4109:29)
    at onInput (VM3144 inputotp.esm.js:4115:9)
    at Object.onInput (VM3144 inputotp.esm.js:4188:24)
    at onInput (VM3144 inputotp.esm.js:3963:32)
    at HTMLUnknownElement.callCallback (react-dom.development.js:20565:14)
    at Object.invokeGuardedCallbackImpl (react-dom.development.js:20614:16)
    at invokeGuardedCallback (react-dom.development.js:20689:29)
    at invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:20703:25)
    at executeDispatch (react-dom.development.js:32128:3)
    at processDispatchQueueItemsInOrder (react-dom.development.js:32160:7)
    at processDispatchQueue (react-dom.development.js:32173:5)
    at dispatchEventsForPlugins (react-dom.development.js:32184:3)
    at eval (react-dom.development.js:32374:12)
    at batchedUpdates$1 (react-dom.development.js:24953:12)
    at batchedUpdates (react-dom.development.js:28844:12)
    at dispatchEventForPluginEventSystem (react-dom.development.js:32373:3)
    at dispatchEvent (react-dom.development.js:30141:5)
    at dispatchDiscreteEvent (react-dom.development.js:30112:5)
```
![Screenshot 2024-04-21 020924](https://github.com/primefaces/primereact/assets/68063809/42d26de5-ce82-4482-af62-45e4b04ac5b4)

### PrimeReact version

10.6.3

### React version

18.x

### Language

TypeScript

### Build / Runtime

Next.js

### Steps to reproduce the behavior

**Type in any value into `InputOtp` or try to remove any value from it.**

**Comment by melloware** [comment]
Thanks for the PR!
