### ISSUE TITLE
DataTable - expandableRowGroups

### ISSUE THREAD

**Issue by Nandovga** [primefaces/primereact#6989]
### Describe the bug

When using the ´expandableRowGroups´ option of the DatabTable console component, it presents this error:

```
react-dom.development.js:86 Warning: Received `false` for a non-boolean attribute `unstyled`.

If you want to write it to the DOM, pass a string instead: unstyled="false" or unstyled={value.toString()}.

If you used to conditionally omit it with unstyled={condition && value}, pass unstyled={condition ? value : undefined} instead.
    at svg
    at http://localhost:5173/node_modules/.vite/deps/primereact_datatable.js?v=c26ac845:9214:22
    at button
    at http://localhost:5173/node_modules/.vite/deps/primereact_datatable.js?v=c26ac845:12238:20
    at td
    at tr
    at tbody
    at http://localhost:5173/node_modules/.vite/deps/primereact_datatable.js?v=c26ac845:12306:20
    at table
    at http://localhost:5173/node_modules/.vite/deps/primereact_datatable.js?v=c26ac845:5388:20
    at div
    at div
    at http://localhost:5173/node_modules/.vite/deps/primereact_datatable.js?v=c26ac845:15535:25
    at div
    at Box (http://localhost:5173/@fs/C:/laragon/www/orangesix/react/src/box/box.tsx:18:23)
    at Table (http://localhost:5173/@fs/C:/laragon/www/orangesix/react/src/table/table.tsx?t=1722883169941:30:43)
    at div
    at Box (http://localhost:5173/@fs/C:/laragon/www/orangesix/react/src/box/box.tsx:18:23)
    at Core
```

### System Information

    "primereact": "^10.8.1",
    "react": "^18.3.1",
    "react-dom": "^18.3.1",

**Comment by melloware** [comment]
10.8.2 is released and this warning should be gone.
