### ISSUE TITLE
p-dialog-mask  zIndex very less

### ISSUE THREAD

**Issue by bloodykheeng** [primefaces/primereact#7274]
### Describe the bug

@melloware issue is still there prime react 10.6.6 . i was using the image component with a preview on a map marker (leaflet js) but i noted when i click on a map marker it opens a popup where i display the primereact image component and the primereact image component has preview enabled .

preview works when my map is not in full screeen but when i put it in full screen i get error. So the problem happens when i try to preview image when ive opened the map in full screen

am using this to show map in full screen
import "leaflet-fullscreen";
import "leaflet-fullscreen/dist/Leaflet.fullscreen.js";
import "leaflet-fullscreen/dist/leaflet.fullscreen.css";

what i noted the maps z index is greater than the image preview z index so the image shows behind the map when am in the maps view full screen and when i try to preview the image in full screen and so the image previews but it comes behind the map

so when i try to open another image when the first image is still open behind the map i get this error

Unexpected: global esc key listener with priority [400, 0] already exists.
at Object.addListener (http://localhost:3000/static/js/bundle.js:342549:13)
at http://localhost:3000/static/js/bundle.js:342570:38
at commitHookEffectListMount (http://localhost:3000/static/js/bundle.js:408788:30)
at commitPassiveMountOnFiber

i need some help here how can i set the image preview zIndex such that i make it greater than the map am using leaflet for my maps

### System Information

```Shell
"primeflex": "^3.3.1",
        "primeicons": "^7.0.0",
        "primereact": "^10.6.6",
        "react": "^18.3.1",
```

### Steps to reproduce the behavior

create a react leaflet js map
put there a popup maker 
on the maker add there prime react  image with preview true 
run app

open map view it in fullscreen 
click marker now try to preview image in full screen uill see that its not shown 
but if u close the map uill see the image

### Expected behavior

p-dialog-mask  should have  a higher zIndex always or give us options to set the zIndex in image and diaglogs

**Comment by sja-cslab** [comment]
Relates to #7220 fixed in #7228 but different component.

**Comment by melloware** [comment]
Agreed
